project:
  type: website
  output-dir: docs
  resources:
    - "files/*"
    - ".nojekyll"
    - "_extensions/*"
    - "_extensions/quarto-ext/fontawesome/"

date2: Feb 7, 2025

website:
  title: "Ajinkya Kokandakar"
  repo-url: https://github.com/ajinkya-k/ajinkya-k.github.io
  navbar:
    right:
      - file: index.qmd
        text: Home
      - text: Papers
        href: index.qmd#preprints-and-working-projects
      - text: CV
        file: files/cv.pdf
      - file: libexp.qmd
        text: Resources
      - file: funstuff.qmd
        text: Fun Stuff
      - icon: github
        href: https://github.com/ajinkya-k
      - icon: envelope
        href: mailto:ajinkya@stat.wisc.edu
      - file: opensource.qmd
        text: Code
      - file: posts/index.qmd
        text: Posts
    collapse: true
  page-footer:
    left:
      - text: "Based on the Ember theme from Alex Hayes's website"
        href: https://www.alexpghayes.com/
    center:
      - text: "Last Updated on: {{< meta date2 >}}"
    right:
      - text: website source
        href: https://github.com/ajinkya-k/ajinkya-k.github.io

format:
  html:
    theme:
      light: [litera, ember.scss, stylesv.scss]
      dark: [litera, stylesv.scss, theme-dark.scss, ember.scss]
    css: styles.css
    toc: true
    anchor-sections: true
    fontsize: 1em



