project:
  type: website
  output-dir: docs
  resources:
    - "files/*"
    - ".nojekyll"

website:
  title: "Ajinkya Kokandakar"
  navbar:
    right:
      - file: index.qmd
        text: Home
      - file: libexp.qmd
        text: Resources
      - file: funstuff.qmd
        text: Fun Stuff

format:
  html:
    theme:
      light: [litera, ember.scss]
      dark: [litera, theme-dark.scss, ember.scss]
    css: styles.css
    toc: true



