## Podcasts

The majority of my free time is spent reading something or listening to something.

<details>
<summary> **Podcasts I like** </summary>


I love podcasts! I discovered the magical world of podcasts sometime in 2017. Haven't stopped since.
My podcast app of choice is [Pocket Casts](https://pocketcasts.com/).
A sample of some great podcasts: 

- [Seen and the Unseen](https://seenunseen.in/) 
    by [Amit Varma](https://amitvarma.com/): 
    <br>India specific podcast, lots of social science and philosophy. 
    Long form ([sometimes > 5hr long](https://twitter.com/amitvarma/status/1376048619548073988?s=20)) interview/discussion.

- [Zero](https://www.bloomberg.com/green-zero-emissions-podcast) by [Akshat Rathi](https://akshatrathi.com/):
    <br>explores the policies, tactics and clean technologies taking us to a future of zero emissions as the world fights climate change. Climate reporter Akshat Rathi talks to the people who are making it happen. Produced by Bloomberg Green.

- [Empire](https://linktr.ee/empirepod) 
    by [Anita Anand](https://anitaanand.net/) and [William Dalrymple](https://twitter.com/DalrympleWill): 
    <br>A great podcast about empires and their history.

- [The Anthropocene Reviewed](https://soundcloud.com/theanthropocenereviewed) 
    by the incredible [John Green](https://www.johngreenbooks.com/): 
    <br>This is my favorite podcast, by a country mile!

- [Grand Tamasha](https://www.grandtamasha.com) 
    hosted by [Milan Vaishnav](https://carnegieendowment.org/experts/714):
    <br> Discusses the latest developments in Indian politics, economics, foreign policy, society, and culture for a global audience

- [Ideas of India](https://www.discoursemagazine.com/tag/ideas-of-india-podcast/)
    by [Shruti Rajagopalan](https://shrutiraj.com/):
    <br>Economis Shruti Rajagopalan examines the ideas that will propel India forward, via conversations with researchers and top thinkers in social science and beyond.

<!--
- [Dear Hank and John](https://dear-hank-john-a5cf29b8.simplecast.com/) 
    by [Hank](https://hankgreen.com/) and 
    [John Green](https://www.johngreenbooks.com/): 
    <br>where the two brothers answer your questions, give you dubious advice, and bring you the news from Mars and AFC Wimbledon. Seriously just try it!

- [Left, Right and Centre](https://www.kcrw.com/news/shows/left-right-center): 
    <br>In (former host) Josh Barro's words - 
    "your civilized yet provocative antidote to the self-contained opinion bubbles that dominate political debates"
-->

- [Computing Up](https://computingup.com/)
    with [Michael Littman](https://www.littmania.com/) and [Dave Ackley](https://twitter.com/livcomp): 
    <br>Conversations about computing writ large
<!--
- [Capitalisn't](https://www.capitalisnt.com/) 
    with [Luigi Zingales](https://faculty.chicagobooth.edu/luigi-zingales) and [Bethany McLean](https://twitter.com/bethanymac12): 
    <br>economics podcast that talks about what's working in capitalism and what isn't
-->
- [Casual Inference](https://casualinfer.libsyn.com/)
    hosted by [Lucy D’Agostino McGowan](https://www.lucymcgowan.com/) and Ellie Murray: 
    <br>podcast about statistics, causal inference, epidemiology, and a bunch of related things. 

- [The Gerrymandering Project](https://fivethirtyeight.com/tag/the-gerrymandering-project/)
    by the good folks at FiveThirtyEight and also [Dave Wasserman](https://twitter.com/redistrict): 
    <br>podcast (plus interactives) about the fascinating complexities of gerrymandering and more importantly self-sorting! 

- [Rachman Review](https://www.ft.com/rachman-review)
    with [Gideon Rachman](https://twitter.com/gideonrachman): 
    <br>A podcast about international politics by the Financial Times. 

- [Sway](https://www.nytimes.com/column/sway) 
    with [Kara Swisher](https://twitter.com/karaswisher): 
    <br>Interview podcast unpacking power and technology

- [Volts](https://www.volts.wtf/)
    by [David Roberts](https://twitter.com/drvolts):
    <br>A newsletter/podcast about clean energy and politics. (Pretty wonky, which is why I love it!)
</details>

## Books

I read a lot, with occasional droughts. My Goodreads profile, 
which can be found [here](https://www.goodreads.com/user/show/16471733-ajinkya-kokandakar), 
is reasonably up to date.

### Where to get books?

#### Libraries

I love libraries! I frequently use the [University of Wisconsin--Madison libraries](https://www.library.wisc.edu/) and the [Middleton Public Library](https://www.midlibrary.org/).
Both have a vast collection of audiobooks and eBooks that are made available through [Libby](https://libbyapp.com/).
If you live in the US, chances are your local library provides eBooks and audiobooks through Libby.
The Middleton Public Library also provides audiobooks and eBooks via [Hoopla Digital](https://www.hoopladigital.com/).
In fact the local library near you may even offer free access to movies, TV shows and documentaries through [Kanopy](https://www.kanopy.com/en/signup).


#### Buying Physical Books

If you want to buy physical copies, I highly recommend [BookFinder](https://www.bookfinder.com/). Its a search engine that collates a list of online stores where the book you want is available sorted by price (and categorized by used/new).
It is perhaps the best way to find the cheapest copy of a book available for sale online.